org.gradle.jvmargs=-Xmx1G

# Build
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
loom_version=1.17.12

# Fabric API
fabric_api_version=0.141.4+1.21.11

mod_version=1.5.0
maven_group=com.oscimate.firorize
archives_base_name=firorize
modmenu_version=17.0.0
text_placeholder_api_version=2.8.2+1.21.10

# Project Metadata
project_name=Firorize
project_url=https://github.com/RuffleSteels/Firorize
# default_release_type can be stable, beta, or alpha
default_release_type=stable
game_versions=1.21.11
required_dependencies=fabric-api
optional_dependencies=modmenu
slug=firorize

modrinth_id=LXDmuHJP
curseforge_id=504744
