name: Release
on:
  workflow_dispatch:
    inputs:
      changelogCommits:
        description: "Commit SHAs to include in the changelog (space/comma separated)"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./gradlew build publishMods -PchangelogCommits="${{ inputs.changelogCommits }}"
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
